# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelApp

  target 'MarvelAppTests' do
    inherit! :search_paths
    pod 'Alamofire', '~> 5.0.0-rc.3'
  end

  target 'MarvelAppUITests' do
    # Pods for testing
  end

end
