# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarvelApp' do
  
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '13.0'
  
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelApp
  pod 'Alamofire', '~> 4.9'
  pod 'AlamofireImage', '~> 3.5'
  pod 'RxSwift', '~> 5'
  pod 'RealmSwift'
  pod "GSImageViewerController"

  target 'MarvelAppTests' do
    inherit! :search_paths
  end

  target 'MarvelAppUITests' do
    # Pods for testing
  end

end
